name: drive
description: DriveThruCLI that communicates with the Google Drive
version: 1.0.0

environment:
  sdk: ^3.0.4

executables:
  drive:

dependencies:
  dotenv: ^4.1.0
  googleapis: ^11.2.0
  googleapis_auth: ^1.4.1
  http: ^1.0.0
  json2yaml: ^3.0.1
  path: ^1.8.3
  prompts: ^2.0.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.0.0
