name: drive
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.0.4

executables:
  drive:

dependencies:
  dotenv: ^4.1.0
  googleapis: ^11.2.0
  googleapis_auth: ^1.4.1
  http: ^1.0.0
  prompts: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
